name: claimease
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.6
  syncfusion_flutter_pdfviewer: ^26.2.5
  pdf: ^3.11.0
  image_picker: ^1.1.2
  pdf_manipulator: ^0.5.0
  pdf_render: ^1.4.9
  url_launcher: ^6.0.20
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/